✨ 신고하기 모달, 공통 컴포넌트(체크박스, 라디오) 구현, 피드 신고 모킹 API Handler 추가
CollaBu/pennyway-client-webview-next pull request #13
Opened 2024-10-27 09:17 UTC by suhwan2004

## CheckList

- [ ] `gap`을 이용하여 자식 요소간의 간격을 제어하였나요? (iOS 14 미지원으로 gap -> space between 적용)

## 작업 이유

-신고하기 기능 추가 필요로 인해 신고하기 모달 구현
-신고하기 및 다른 영역에서도 사용되는 공통 컴포넌트인 radio, checkbox 구현
-신고하기 기능에 사용될 모킹 필요로 인한 모킹 api handler 추가

<br/>

## 작업 사항

### 1️⃣ 신고하기 모달 구현

신고하기 모달의 경우, 특정 비즈니스 로직(피드를 신고하는 것)이 담겨 있기 때문에 feature 폴더에 위치해두었습니다!
신고하기 클릭 시 동작되는 api 로직의 경우 모킹 api를 넣어둔 상태입니다. 

### 2️⃣ 공통 컴포넌트 ( 체크박스, 라디오 ) 구현

둘 다 shared에 위치해두었습니다.특이사항은 없으나 체크박스의 경우, 좋아요(빈하트, 채워진 하트)등으로 앞으로 아이콘의 확장 여지가 있는 것 같습니다. 라디오도 엄청 늘어나진 않겠지만 어느정도 동일한 것 같구요.

다만, on, off 아이콘을 prop으로 넘겨 뭔가 자율성?을 보장해줄까? 라는 생각을 하다가... 그런 케이스도 많이 없는 것 같고, 왠만해선 정형화된 쌍을 이루는 것 같아서

필요한 때에 따라 checkbox의 consts/index.ts에 추가하는 것으로 해결하자!라는 생각을 하긴 했는데 여러분의 생각이 궁금합니다.

### 3️⃣ 피드 신고 모킹 API Handler 추가

피드 신고기능에 사용할 모킹 API Handler를 추가했습니다. 템플릿 및 설정은 금일 PR로 올려주신 부분을 어느정도 참고해서 개발을 진행했고, 실제 신고하기 모달을 띄워 모달 로직 포함 모킹 API까지 특이사항 없이 잘 동작됨을 확인했습니다.(병준님 감사합니다...)

현재, PR로 올려주신 MSW 코드 부분과 어느정도 비슷한 파일 위치들을 건드리고 있어서 Merge Conflict가 일어날 예정인데요.
요 부분은 병준님 PR이 Main에 들어간 이후에 자체적으로 Conflict 를 해결하고 squash merge 예정입니다. 

만약 신고하기 모달을 포함한 신고하기 모킹 API까지 확인을 원하실 경우 page.tsx에 다음과 같은 코드를 넣어주심 확인이 가능할 것 같습니다.

script 영역 추가 코드
```
  const [isReportModalVisible, setIsReportModalVisible] = useState(true);
  const [reported, setReported] = useState(false);
  const feedId = 123;

  const cancelReportModal = () => {
    setIsReportModalVisible(false);
  };

  const reportFeed = () => {
    setIsReportModalVisible(false);
    setReported(true);
    console.log(reported);
    alert('신고가 완료되었습니다.');
  };
```

return 내 태그 영역에 추가 코드
```
        <ReportModal
          isVisible={isReportModalVisible}
          feedId={feedId}
          onCancel={cancelReportModal}
          onReport={reportFeed}
        />

```

이렇게 적고보니 또 한 PR에 많은 것을 넣어버렸네요... 다음부터 분량 조절을 제대로 진행하겠습니다!

<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분

- [ ] 신고하기 모달의 이 올바른 폴더 위치에 정의되었는지
- [ ] 컴포넌트들의 구현 코드 상 특이사항이 있는지
- [ ] 신고하기 모킹 부분에 특이사항이 있는지

  <br/>

## 발견한 이슈

없음

2024-10-27 13:51 UTC, BangDori reviewed
- 1️⃣ 신고하기 모달 구현
- 3️⃣ 피드 신고 모킹 API Handler 추가
- 4️⃣ 스토리북 내에서 MSW 사용되도록 세팅 및 @storybook/preview-api 설치

리뷰할 내용이 너무 많아 저 혼자 리뷰하기에는 무리라고 판단하여 위 내용들에 대해서만 리뷰를 진행하였습니다! 나머지 2️⃣ 공통 컴포넌트 ( 체크박스, 라디오 ) 구현에 대해서는 @Legitgoons 님께.. 토스하겠습니다.

2024-10-27 13:51 UTC, BangDori commented on app/page.tsx
> +export default function Home() {
P5: 앗 제가 실수로 async를 안지웠군요 ㅋ큐ㅠ 지워주셔서 감사합니다

2024-10-27 13:51 UTC, BangDori commented on .storybook/preview.ts
P5: storybook & msw 연동 작업 언제 할까나 했는데, 미리 추가해주셔서 감사합니다 ㅎㅎ

2024-10-27 13:51 UTC, BangDori commented on src/app/mocks/data/report.ts
P4: 이 파일은 삭제해도 되지 않을까요?

2024-10-27 13:51 UTC, BangDori commented on src/features/reportModal/consts/index.ts
> +export const reportCategories: string[] = [
P4: `reportCategories` 배열 내부의 값들이 모두 `string` 타입으로 이루어져 있어 타입을 명시해주지 않아도 되지 않을까?라는 생각이 드는데 타입을 추가해주신 이유가 따로 있으신가요?

2024-10-27 13:51 UTC, BangDori commented on src/features/reportModal/index.ts
P5: features 레이어는 수환님의 말씀대로 비즈니스 가치를 가지는 사용자 시나리오나 기능을 다루는 레이어이기 때문에 현재 위치가 적합하다고 생각합니다!

2024-10-27 13:51 UTC, BangDori commented on src/features/reportModal/ui/ReportModal.stories.tsx
> +    const [{ isVisible }, updateArgs] = useArgs();
P5: `@storybook/preview-api` 라이브러리의 useArgs 훅스를 사용함으로써 스토리북 컴포넌트 내부에서 값을 입력할 수 있게 된건가요?

2024-10-27 13:51 UTC, BangDori commented on src/features/reportModal/ui/ReportModal.tsx
> +  const contentMaxLength = 80;
P3: 콘텐츠 최대 길이 값은 가변적인 값이 아닌 고정된 값이기에 컴포넌트 내부에서 선언해주지 않아도 될 것 같아요! `consts/index.ts`에 위치시켜도 되지 않을까요?

2024-10-27 13:51 UTC, BangDori commented on src/features/reportModal/ui/ReportModal.tsx
> +  };
P5: API 연동은 티켓을 따로 분리하여 작업하시는 게 리뷰하는 것도 더 편할 것 같아서 해당 PR에서는 상세히 리뷰하지 않겠습니다!

2024-10-27 13:51 UTC, BangDori commented on src/features/reportModal/ui/ReportModal.tsx
> +            ></textarea>
P3: textarea 내부에 들어오는 태그가 없다면 셀프 클로징 태그를 이용해서 바로 닫아줘도 되지 않을까요?

2024-10-27 13:51 UTC, BangDori commented on src/features/reportModal/ui/ReportModal.tsx
P3: 현재 스토리북에 나온 신고하기 모달창의 너비가 280으로 나와있는데 스토리북에서는 모달창의 너비가 390으로 나와있는 거 같아요! 확인 부탁드려요

2024-10-27 13:51 UTC, BangDori commented on src/app/mocks/handlers/feed.ts
> +  http.post('http://api.example.com/v2/feeds/:feedId/reports', async ({ request, params }) => {
P5: 현재 신고하기 api에 대해서 isBlind에 대한 처리가 추가되어 있지 않은 거 같은데, Feed 모킹 데이터가 추가된 이후에 isBlind 값을 적용할 예정이실까요?

2024-10-28 00:09 UTC, suhwan2004 commented on src/app/mocks/data/report.ts
앗! 넵 맞습니다... 뭔가 report 목데이터가 필요할까 생각해서 일단 만든건데 빠르게 제거해둘께요! 감사합니다

2024-10-28 03:11 UTC, suhwan2004 commented on src/features/reportModal/consts/index.ts
> +export const reportCategories: string[] = [
앗 또 습관성 명시적 지정을... 수정해둘께요!

2024-10-28 03:13 UTC, suhwan2004 commented on src/features/reportModal/ui/ReportModal.stories.tsx
> +    const [{ isVisible }, updateArgs] = useArgs();
아뇨! 정확히는
스토리북에서 신고모달에서 신고하기를 눌러서 모달창이 닫힐 때 화면 아래 control 영역 내 isVisible이 따라서 false가 되도록 변경된 거에요!
 => 원래는 모달창이 닫혀도, 계속 true로 유지되는 문제가 있었습니다

2024-10-28 03:15 UTC, suhwan2004 commented on src/features/reportModal/ui/ReportModal.tsx
> +  const contentMaxLength = 80;
consts를 생각 못했었군요... 빠르게 수정해두겠습니다!

2024-10-28 03:16 UTC, suhwan2004 commented on src/features/reportModal/ui/ReportModal.tsx
> +            ></textarea>
넵! 빠르게 수정해두겠습니다

2024-10-28 03:28 UTC, suhwan2004 commented on src/app/mocks/handlers/feed.ts
> +  http.post('http://api.example.com/v2/feeds/:feedId/reports', async ({ request, params }) => {
아아 제가 이해한 것으로는 isBlind에 대한 처리를 handlers에서 하지 않아도 괜찮을 것 같아서 일단은 별도 처리를 하지 않았던 것 같아요

신고하기 성공 이후에, 신고하기 모달이 사라지면서 해당 게시글을 보여줄지 안보여줄지는 부모컴포넌트인 피드 페이지가 동작해야되는 구조이기 때문입니다!
(다만, 위의 처리를 하려면 onReport에 feedId와 isBlind를 넘겨줬어야 됬는게 그에 대한 처리가 없었네요... 추가해두겠습니다!)

혹시, 만약 isBlind를 handler에서 처리한다면 어떻게 처리될지 병준님의 의견을 여쭤봐도 될까요??

2024-10-28 03:32 UTC, suhwan2004 commented on src/features/reportModal/ui/ReportModal.tsx
아! 현재, 신고하기 모달의 경우, 고정된 width로 대응하지 않고, margin left, right를 5로 줘서 기기별 screen width 에 따라 자연스레 늘어나게 개발해두었습니다! 

혹시, 해당 개발사항 관련되서 고정된 pixel로 적용해두어야 할까요??

2024-10-28 10:01 UTC, BangDori commented on src/features/reportModal/ui/ReportModal.stories.tsx
> +    const [{ isVisible }, updateArgs] = useArgs();
아하 그렇군요, 친절하게 설명해주셔서 감사합니다!

2024-10-28 10:03 UTC, BangDori commented on src/features/reportModal/ui/ReportModal.tsx
> +  const contentMaxLength = 80;
그리고 저희 [상수명 규칙](https://github.com/CollaBu/pennyway-client-webview-next/wiki/Naming-Rule#6-%EC%83%81%EC%88%98%EB%AA%85)은 대문자와 snake_case를 이용하기로 했었는데 이거에 맞게 상수명을 수정해야할 것 같아요!

2024-10-28 10:25 UTC, BangDori commented on src/features/reportModal/ui/ReportModal.tsx
<div align="center">
  <img src="https://github.com/user-attachments/assets/642a71f4-21e4-4cb7-b879-3b606fbf89a1" width="360" />
</div>

저도 화면의 너비가 커짐에 따라 모달창의 크기도 화면의 비율에 맞춰 대응해주면 좋다고 생각해요! 그런데 위 이미지처럼 신고 사유 목록의 크기나 위치도 비율에 맞게 대응해주지 않으면 빈 여백이 너무 많이 생겨버려서 저는 너비 280으로 고정하면 될 거 같다고 생각이 들긴 하거든요.

그래서 이 부분은 저희 둘이서 리뷰에서 정하기 보다는 재서님께 여쭤봐야 할 것 같아요.

2024-10-28 10:40 UTC, BangDori commented on src/app/mocks/handlers/feed.ts
> +  http.post('http://api.example.com/v2/feeds/:feedId/reports', async ({ request, params }) => {
어떻게 처리할 지에 대해 이야기하기 전에 잠깐 모킹 API를 사용하는 저의 개인적인 이유는 다음과 같은데요.

1. FE 주도 개발 (빠른 생산성)
2. MSW를 이용한 비즈니스 로직 테스트

우선 현재 저희는 1번 상황이기에 DB와 유사하게 관계를 갖게 하는거 보다는 단순하게 피드 목록이 추가된다면 피드 목록의 원본 배열에서 신고된 feedId의 값에 대해 참조하여 isBlind 값을 아래와 같이 true로 변경시켜줄 것 같아요.

```ts
function blindFeed(feeds: Feed[], feedId: number) {
  feeds.forEach(feed => {
    if (feed.id === feedId) {
      feed.isBlind = true;
    }
  });
}

const feeds = [
  { id: 1, isBlind: false },
  { id: 2, isBlind: false },
  { id: 3, isBlind: false },
];

blindFeed(feeds, 2);
```

2024-10-28 10:48 UTC, suhwan2004 commented on src/features/reportModal/ui/ReportModal.tsx
> +  const contentMaxLength = 80;
앗 상수 정의가 거의 없다보니, 깜빡해버렸군요... 빠르게 수정해두겠습니다!

2024-10-28 10:53 UTC, suhwan2004 commented on src/features/reportModal/ui/ReportModal.tsx
아... 이게 저 라디오 + 글씨에 122px를 할당된 상태라, 344px 이상이면 위로 올라갈텐데, 확실히 보면 width별로 살짝 애매하게 안 올라가는 케이스가 존재하네요...

말씀대로, 일단 이 신고모달 관해서는 재서님께 자문을 구하는게 맞는 것 같아요. 좋습니다!

2024-10-28 11:14 UTC, suhwan2004 commented on src/app/mocks/handlers/feed.ts
> +  http.post('http://api.example.com/v2/feeds/:feedId/reports', async ({ request, params }) => {
아아 어떤 말씀이신지 이해했습니다. 처음에 isBlind값을 언제 적용할 것인지 여쭤보신 것도 이 부분 때문이였군요!

만약에 메인 피드 페이지에서 feed.ts에있는
export const feedMockData = generateFeedMockData(100);를 피드 페이지에서 사용한다면 

신고하기 API 코드는 이대로 두되, blindFeed를 mocks/data/feed.ts에 생성하여 특정 ID가 블라인드 처리된 Mock Data를 받아올 수 있게 처리하고

메인 피드 페이지에서 onReport 파라미터로 blindFeed를 넘겨주는게 맞겠네요.
저도 현재 MSW를 사용하는 이유에 대해 1번에 크게 공감합니다. 이 것도 수정해둘게요!

2024-10-28 11:50 UTC, BangDori commented on src/app/mocks/handlers/feed.ts
> +  http.post('http://api.example.com/v2/feeds/:feedId/reports', async ({ request, params }) => {
숨기기 여부를 나타내는 isBlinded(과거형) 필드를 추가하는 것 좋은 거 같아요!

> 신고하기 API 코드는 이대로 두되, blindFeed를 mocks/data/feed.ts에 생성하여 특정 ID가 블라인드 처리된 Mock Data를 받아올 수 있게 처리하고
>
> 메인 피드 페이지에서 onReport 파라미터로 blindFeed를 넘겨주는게 맞겠네요.

이 부분이 이해가 잘 되지 않는데, 특정 ID가 블라인드 처리된 배열을 하나 더 생성하고 해당 배열을 피드 목록 조회할 때 사용하신다는 말씀이실까요?

2024-10-28 12:33 UTC, suhwan2004 commented on src/app/mocks/handlers/feed.ts
> +  http.post('http://api.example.com/v2/feeds/:feedId/reports', async ({ request, params }) => {
먼저 mocks/data/feed.ts에 이러한 함수를 하나 만드는 것을 생각했습니다

```
export function blindFeedMockData(feeds : IFeed[], feedId : number) {
  return feeds.map((feed) => {
    if(feedId === feed.id){
      feed.isBlinded = true
    }
    return feed
  })
}
```

다음으로 ReportModal을 사용한 Page.tsx 코드가 있다면 이렇게 처리가 되면 어떨까? 생각했던 것 같아요

```

export default function Home() {
  const [feeds, setFeeds] = useState([])
  
  useEffect(() => { 대략적으로 feed 조회하는 로직이 있을 예정입니다 }, [])
  
  return (
    <PageContainer
      headerProps={{
        left: <IconArrowFront width="44" height="44" />,
        center: <div className="text-black">메인페이지</div>,
        right: <button className="w-[44px] h-[44px] pr-2 text-black">게시</button>,
      }}
    > 
      <ReportModal 
        isVisible={true}
        feedId={12}
        onCancel={() => {}}
        onReport={() => {
          //실제로는 다시, 피드 조회를 재호출 할 것이나, DB가 없고, 피드조회에는 블라인드될 feed id를 받는 prop이 없을 것이기에
          // 대신 blindFeedMockData를 통해 가려진 새 배열을 가져옵니다! 이건 신고하기가 성공되고 실행!
          setFeeds([...blindFeedMockData(feeds, 12)])
        }}
      />
      
  </PageContainer>
);
}
```

2024-10-28 14:01 UTC, BangDori commented on src/app/mocks/handlers/feed.ts
> +  http.post('http://api.example.com/v2/feeds/:feedId/reports', async ({ request, params }) => {
근데 이렇게 해버리면 최상위 레이어인 app에 위치한 blindFeedMockData 메서드를 호출해야해서 문제가 생길 것 같아요!

제 생각에는 mocks를 하나의 가짜 서버라고 생각하고 mocks 에서 사용할 blindFeedMockData 메서드, src 내부에서 사용될 blindFeed 따로 메서드로 생성하는 건 어떨까요?

동일한 로직을 처리하는 메서드이긴 하지만 메서드가 가지는 의미(서버단에서 수행하는 것과 클라이언트단에서 수행하는 것)가 다르기에 큰 문제가 되지는 않는다는 생각이 들어요. 어떻게 생각하시나용??

2024-10-28 15:32 UTC, Legitgoons requested changes
수고 많으셨습니다. 간단한 질문과 convention 관련된 부분 몇 가지 남겼습니다!

2024-10-28 15:32 UTC, Legitgoons commented on src/shared/ui/checkbox/ui/Checkbox.tsx
> +  shape?: keyof typeof checkboxShapes;
P5: 저는 공통 컴포넌트 만들면서 무지성으로 union type을 갈겼었는데, consts에서 Type을 가져와서 쓰니 한결 낫네요..😅 한 수 배웠습니다

2024-10-28 15:32 UTC, Legitgoons commented on src/shared/ui/checkbox/ui/Checkbox.tsx
> +  setIsChecked: React.Dispatch<React.SetStateAction<boolean>> | setIsCheckedFunc;
P5: 이 부분은 state로 사용할 때와 그렇지 않을 때를 고려해서 union Type으로 지정해주신거군요! 흥미롭습니다.

2024-10-28 15:32 UTC, Legitgoons commented on src/shared/ui/checkbox/ui/Checkbox.tsx
> +type setIsCheckedFunc = (value: boolean) => void;
P2: type에는 T를 붙이고 Pascal case로 작성해주셔야합니다!

2024-10-28 15:32 UTC, Legitgoons commented on src/shared/ui/radio/ui/Radio.tsx
> +  changeSelected: () => void;
P4: 여기서는 void를 return하는 함수만을 type으로 지정해주신 이유가 `radio는 checkbox와 다르게 여러개의 값을 가질 수 있기에 어떤 상태값이 들어올지 명확하지 않아서` 인가요?

2024-10-29 14:41 UTC, suhwan2004 commented on src/shared/ui/checkbox/ui/Checkbox.tsx
> +type setIsCheckedFunc = (value: boolean) => void;
감사합니다! 빠르게 수정해둘게요

2024-10-29 14:57 UTC, suhwan2004 commented on src/shared/ui/radio/ui/Radio.tsx
> +  changeSelected: () => void;
넵! 맞습니다. 예를들어 신고하기 모달에서도 라디오 선택 요소들이 엄청 많기 때문에


1. 그 중 하나를 선택해서 onChange 이벤트가 동작되면서 changeSelected 안에 있는 함수 실행으로 카테고리 상태가 바뀜


2. Radio를 "신고 카테고리 항목 배열"을 map 렌더링 할 시에 isSelected(radio의 value)가 true인지 false인지를 다음과 같이 판단하기에

 방금 바뀐 카테고리 상태값 === 현재 배열 인덱스의 카테고리 값
 
선택한 것에 해당하는 라디오의 value가 바뀜


이런 식으로 통제하기 위해 changeSelected라는 void 함수를 받아서 해결하자!가 된 것 같습니다.

2024-10-29 15:09 UTC, BangDori commented on src/features/reportModal/ui/ReportModal.tsx
> +  const contentMaxLength = 80;
넵 상수명 확인되는대로 바로 resolve 하겠습니다!

2024-10-29 15:41 UTC, suhwan2004 commented on src/app/mocks/handlers/feed.ts
> +  http.post('http://api.example.com/v2/feeds/:feedId/reports', async ({ request, params }) => {
말씀주신 부분 생각해보고, fsd 찾아보면서 고민해보았는데,

bilndFeedMockData의 경우, 최상단 mocks 폴더에 그대로 존재하고
blindFeed의 경우, feature에 특화된 기능이라기보다는 reportModal에 쓰는 pages에서 쓰이는 정도로 범용적으로 쓰이기에 shared/lib/mocks 폴더 내에 feed.ts를 생성하여 넣어두었습니다!
 => 라는 생각에 shared에 넣어둔 상황인데, 이에 대한 병준님의 의견도 궁금합니다

IFeed, IImage를 그대로 현재 파일에 넣어둔 상황인데, mocks에서 사용되는 타입이 어디에 두는가? 에 대해 아직 협의가 나오지 않아 현재는 임시적으로는 파일 내 재생성을 해둔 상태입니다!

2024-10-30 04:04 UTC, Legitgoons approved these changes
수고 많으셨습니다! 병합하셔도 좋습니다!

2024-10-30 12:29 UTC, BangDori commented on src/app/mocks/handlers/feed.ts
> +  http.post('http://api.example.com/v2/feeds/:feedId/reports', async ({ request, params }) => {
음.. 우선 FSD Architecture에서 권장은 폴더 구조는 크게 Layers, Slices, Segments 이렇게 max 4 depth(layer/slice/segment/index.ts)를 가지는게 정상적인 구조인 것으로 알고 있는데요. 현재 말씀해주신 폴더에서는 제가 말해준 max depth를 넘어가고 있는 것 같아요.

말씀해주신 mocks에서 사용되는 타입은 어디에 두는가?와 blindFeed의 위치에 대한 고민은 계속 코멘트로 나누기엔 작업이 너무 지연될 거 같아서, 우선 현 상태로 머지하고 토요일 회의에서 같이 얘기 나눠보시면 좋을 것 같습니다!

2024-10-30 12:30 UTC, BangDori approved these changes
고생하셨습니다! 남은 코멘트들은 확인후에 수환님이 resolve 하시면 될 것 같아요!

2024-10-30 14:31 UTC, suhwan2004 commented
일단 Merge 해두었습니다!

mock type, blindFeed의 위치한 이슈
reportModal과 같은 UI들의 화면에 따라가는 반응형 디자인?에 대한 얘기를 주말에 함께 나눠봐야 겠네요...

2024-10-30 14:31 UTC, merged