⚡ 페이지 컨테이너, 모달 컴포넌트, 신고하기 모달 컴포넌트의 폴더 위치 조정
CollaBu/pennyway-client-webview-next pull request #15
Opened 2024-11-03 07:23 UTC by suhwan2004

## CheckList

- [ ] `gap`를 이용하여 flex 컨테이너 내 자식 요소간의 간격을 제어하였나요? (iOS 14 미지원으로 gap -> space-x, space-y 적용)

## 작업 이유
- 어제 회의에서 토의된, 컴포넌트들 별 맞는 폴더 위치의 조정 필요로 해당 작업 진행
- 어제 회의에서 토의된, mock types 위치 조정 및 해당 내용 적용
- IOS 세팅에 대응하여, 화면 Zoom 세팅을 프로젝트 내 적용 필요로 인해 진행

<br/>

## 작업 사항

### 1️⃣ 컴포넌트 별 폴더 위치 조정
어제 회의가 나왔던 내용대로 다음과 같은 폴더 위치 변동이 있었습니다.

신고하기 모달 => widgets 폴더로 이동 
페이지 컨테이너, 모달 => shared/ui로 이동

또한, blindFeed 함수의 경우에는 생각해보니 다음과 같은 상황이기에...
 - feedHandler에서 피드 조회하기를 하는 함수가 존재할 예정이고
 - 동일한 feedMockData를 Import 하여 사용할 것이기에
 
blindFeed는 차주에 작업 예정인 피드 숨기기 mock & ui 구현에서 작업할 예정으로 판단하여 현재는 제거해둔 상황입니다.

### 2️⃣ mock types 위치 조정
마찬가지로 어제 회의가 나온 내용을 토대로 mock typs(IUser, IFeed, IImage)들의 위치 조정을 진행하였습니다!

IUser, IFeed => widgets/{user 또는 feed}/model/type.ts
IImage => shared/types/image.ts

또한, 위 타입들을 사용하는 코드들에 대한 import 또한 수정이 있었습니다.

### 3️⃣ IOS 세팅에 대응하여, 화면 Zoom 세팅을 프로젝트 내 적용
IOS 팀에서 보여주는 화면 UI와 통일된 UI를 제공하기 위해, 체공받은 기기별 화면 배율 설정을 저희 프로젝트에 적용해두었습니다.

SSR 환경에서도 보여야 하는 것을 고려하여, global.css에 작업을 진행해두었습니다.

실제 page.tsx에서 해당 작업이 정상 적용된 것을 확인 했고, body태그에 Zoom을 적용시켜주는 것이기 때문에 storybook에서도 해당 내용이 보이는 것을 확인해두었습니다.

<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분

- [ ] 기존 컴포넌트 및 타입의 폴더 조정 작업에 이상이 있는지
- [ ] global.css 내 정의된 Zoom 작업에 특이사항이 있는지
  <br/>

## 발견한 이슈

X

2024-11-03 14:08 UTC, Legitgoons approved these changes
원인 불명의 이슈때문에 고생이 많으셨습니다. 알다가도 모를 safari.. 쉽지 않네요 ㅋㅋㅋㅋ

2024-11-03 14:08 UTC, Legitgoons commented on app/globals.css
> +  html {
P5: 이 부분에 대해서 궁금한게, 혹시 body에만 주면 어떻게 동작하나요?

2024-11-03 15:21 UTC, suhwan2004 commented on app/globals.css
> +  html {
음... 다시 확인해보니, body에 줄 시에 오늘 discord에 올라왔던 이미지처럼 제대로 zoom을 못받은 것 처럼 나오는 것으로 보이네요...

<img width="903" alt="image" src="https://github.com/user-attachments/assets/d8c8e346-16f0-49f7-a4bd-ed56eb45573d">

2024-11-04 10:22 UTC, BangDori requested changes
신고하기쪽에 빠진 부분이 있는 것 같아요! 확인부탁드려요~~

2024-11-04 10:22 UTC, BangDori commented on src/app/mocks/handlers/feed.ts
> +      if (cur.id === +feedId) {
P5: 숫자 타입으로 변환할 때 항상 명시적 형 변환을 이용해서 `Number(feedId)`와 같은 방식으로 변환했었는데 이런 방식도 있었군요. 이 방식은 명시적 형 변환을 하는 방법과 어떻게 다른건가요?

2024-11-04 10:22 UTC, BangDori commented on src/app/mocks/handlers/feed.ts
> +        cur.isBlinded = true;
P2: 피그마에 나온 UI를 확인해봤을 때 `해당 게시물 숨기기` 체크 여부에 따라 blind 처리가 되어야 할 것 같아요!

<img src="https://github.com/user-attachments/assets/318aee8d-7cee-45de-b383-5ebc95289587" width="360" />

2024-11-04 10:22 UTC, BangDori commented on app/globals.css
P5: 와하,, 전체를 뷰포트에 대해 `zoom`을 이용해서 사이즈를 조절해보는 방법에 대해서는 고려해보지 못했는데 좋네요. 수환갓

2024-11-04 10:22 UTC, BangDori commented on src/app/mocks/handlers/feed.ts
> +        cur.isBlinded = true;
아 추가로 원래 기존에 기획에서는 신고하기 사유만 클릭해도 신고하기가 가능했던걸로 기억하고 있는데, 이 부분도 확인하고 같이 반영하면 좋을 것 같아요! (현재 `pm-질문방`에 업로드해두었어요!)

2024-11-04 10:29 UTC, BangDori commented on app/globals.css
> +  html {
```html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
</html>
```

조심스럽게 추측해보자면 HTML5에서 뷰포트 크기를 조정하기 위해서 위와같이 `head` 태그에 viewport에 대한 `meta` 태그를 정의해주는데, 최상단에 적용한 `zoom`은 뷰포트를 기반으로 화면의 `zoom` 수준을 제어하다보니 아마 `body`에서는 적용되지 않는 것 같습니다!

2024-11-04 12:30 UTC, suhwan2004 commented on src/app/mocks/handlers/feed.ts
> +      if (cur.id === +feedId) {
Number의 경우 명시적으로 형변환 시키나, +의 경우 피연산자를 숫자로 강제로 형변환 시키는 차이점이 존재하는데요. 

저 같은 경우에는 +를 붙여 숫자를 만드는 것의 경우는 위에 있는 cur.id, feedId와 같이 명시적 형 변환까지 안가더라도 코드를 읽는데에 충분히 문제가 없다면 사용하는 것 같습니다.

좀 더 찾아보니까, 
 +로 형변환 시 Number보다 더 빠르다는 내용이 존재하고 
 둘 다 여러 케이스를 비교했을 때 비슷한 결과값을 내준다는 글들도 보이네요! 한번 다들 봐보심 좋을 것 같아요!
 
https://stackoverflow.com/questions/1133770/how-to-convert-a-string-to-an-integer-in-javascript

2024-11-04 12:33 UTC, suhwan2004 commented on src/app/mocks/handlers/feed.ts
> +        cur.isBlinded = true;
어우 감사합니다. 이 부분을 생각했어야 됬는데 챙겨서 넣질 않았네요... 
확인되는대로 수정해서 반영해두겠습니다!

2024-11-04 12:36 UTC, suhwan2004 commented on app/globals.css
저도 이번에 이것저것 보다가 넣어본 건데, 
전에 react native에서 dimension을 구해서, 반응형으로 계산해서 적용시켰던 기억이 있는데, 계산해서 넣는 방식보다 더 눈에 보이기도 깔끔하고 좋은 느낌이라 상당히 맛있습니다...

2024-11-04 15:35 UTC, BangDori commented on src/app/mocks/handlers/feed.ts
> +      if (cur.id === +feedId) {
숫자로 변환하기 위한 방법이 엄청나게 많네요. 제 생각에도 명시적 변환을 해주지 않아도 +로 충분할 것 같아요.

좋은 자료 공유해주셔서 감사합니다!

2024-11-05 12:48 UTC, suhwan2004 commented on src/app/mocks/handlers/feed.ts
> +        cur.isBlinded = true;
디스코드 상 확인 되었던 내용 기반으로, content가 따로 오지 않았더라도 신고되게 수정해두었습니다!

2024-11-05 13:50 UTC, BangDori approved these changes
고생하셨습니당~ 확인 완료했어요!

2024-11-05 13:50 UTC, BangDori commented on src/app/mocks/handlers/feed.ts
P5: contents가 따로 저장되면 좋긴 하겠지만 mock api에서는 굳이 처리해줄 필요 없는 것 같네요!! 고생하셨습니다 !!!!

2024-11-05 13:52 UTC, suhwan2004 commented on src/app/mocks/handlers/feed.ts
넵 뭔가 화면단에서도 신고리스트? 같은 것들이 mock data로써 따로 쓰이는 곳이 없는 것 같아서 일단은 그냥 사용안한 느낌인 것 같아요! 확인 감사합니다~~

2024-11-05 13:53 UTC, merged