⚙️ CI Pipeline 구축
CollaBu/pennyway-client-webview-next pull request #3
Opened 2024-10-08 14:11 UTC by BangDori

## 작업 이유

- 자동화 빌드 및 테스트를 활용한 개발 생산성 개선

<br/>

## 작업 사항

### 1️⃣ CI Pipeline 구조도

단계별 흐름은 아래 이미지와 같습니다. `npm`, `yarn`과 다른 점이 있다면 `pnpm`의 경우 `pnpm`을 추가해주는 Setup pnpm 단계를 거쳐야합니다. 참고로 현재 테스트가 없기 때문에 vitest command의 `passWithNoTests` 옵션을 추가하여 테스트가 통과하도록 설정하였습니다. 

![CI Pipeline](https://github.com/user-attachments/assets/188a1369-e346-4ee4-80b9-da0458723755)

## 리뷰어가 중점적으로 확인해야 하는 부분

- [x] CI 파이프라인 구조가 잘 작성되었나요?
- [x] 추후 테스트코드가 작성됨에 따라 `passWithNoTests`은 제거되어야 합니다.

## 발견한 이슈

### 1. Vite CJS Node API deprecated

vitest 테스트를 진행하였을 때 위 에러가 발생하였는데 package.json의 type을 module로 설정하여 해결하였습니다.

### 2. ESLint 9 - Nextjs 호환성 문제

ESLint 9 버전이 출시된 지 얼마 되지 않아 eslint-config-next의 모든 종속성을 지원하지 않아서 v8.57.0으로 다운그레이드 하였습니다. ESLint9로 lint를 실행하였을 때 발생한 에러 로그는 다음과 같습니다.

```shell
Invalid Options:
- Unknown options: useEslintrc, extensions, resolvePluginsRelativeTo, rulePaths, ignorePath, reportUnusedDisableDirectives
- 'extensions' has been removed.
- 'resolvePluginsRelativeTo' has been removed.
- 'ignorePath' has been removed.
- 'rulePaths' has been removed. Please define your rules using plugins.
- 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.
 ELIFECYCLE  Command failed with exit code 1.
```

### 3. @typescript-eslint/typescript-estree

ESLint의 버전을 v8.57.0으로 다운그레이드한 후 lint를 실행한 결과 `@typescript-eslint/typescript-estree`가 typescript v5.6.2를 공식적으로 지원하지 않는다는 경고 메시지가 표시되어 v5.5.4로 다운그레이드 하였습니다. 경고 메시지 로그는 아래와 같습니다.

```
> pennyway-client-webview-next@0.1.0 lint /Users/mac/Desktop/pennyway-client-webview-next
> next lint

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.2

Please only submit bug reports when using the officially supported version.

=============
✔ No ESLint warnings or errors
```

### 참고

- [vite-cjs-node-api-deprecated](https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated)
- [New ESLint "flat" configuration file does not work with next/core-web-vitals](https://github.com/vercel/next.js/issues/64114)

2024-10-08 14:42 UTC, Legitgoons requested changes
몇 가지 궁금한 부분이 있어 리뷰 남겼습니다!

2024-10-08 14:42 UTC, Legitgoons commented on .github/workflows/install-and-test.yml
> +        run: pnpm lint
P1: lint는 pre-commit 단계에서 이미 교정되어서 들어오는데, 굳이 ci단계에서 또 할 필요는 없지 않을까요?

2024-10-08 14:42 UTC, Legitgoons commented on .github/workflows/install-and-test.yml
> +          run_install: false
P5: 혹시 이 부분은 어떤 동작을 의미하는지 알려주실 수 있나요?

2024-10-08 14:52 UTC, BangDori commented on .github/workflows/install-and-test.yml
> +          run_install: false
해당 부분은 install-and-test를 실행하는 호스팅 실행기에 `pnpm`을 설치하는 단계로 `run_install` 옵션은 npm package 설치 여부를 결정하는 옵션을 나타냅니다. 여기서 옵션을 false로 지정한 이유는 `pnpm`을 호스팅 실행기에 설정하는 단계와 node_modules를 설치하는 단계를 분리하고자 위와 같이 설정하였습니다.

2024-10-08 15:01 UTC, BangDori commented on .github/workflows/install-and-test.yml
> +        run: pnpm lint
제가 CI 단계에 추가한 이유는 크게 2가지가 있습니다.

### 1. 일관성 보장

모든 개발자의 Code Editor에 pre-commit 훅이 **항상** 정상적으로 동작한다고 보장할 수 없기 때문에 CI 파이프라인에 추가하였습니다. 실제로 제가 프로젝트를 진행하는 중 [code 127 error](https://github.com/typicode/husky/issues/1038)가 발생하여 pre-commit이 동작하지 않은 경우가 있었습니다!

### 2. 정적 분석 범위 제한

pre-commit 훅에서는 변경된 파일만을 검사하도록 eslint를 실행하는 것으로 알고 있습니다. 실제로 외부 컴포넌트들에서 import하고 있는 파일명을 변경하고 이를 커밋하면 import 하고 있는 파일들에 대해서는 검사하지 않은 채 커밋이 이루어지게 됩니다. 물론 이 부분은 개발자가 소스 코드를 실행하거나 혹은 직접 확인하면서 수정할 수 있는 부분이지만 개발자의 실수가 일어날 수 있는 부분이라고 판단하였습니다.

제 생각에는 CI 단계에 lint를 추가하는 것이 크게 시간을 소요하지 않기 때문에 사소한 실수라도 잡아내는 것이 좋다고 생각되는데 혹시 어떻게 생각하시나요!?

2024-10-08 15:24 UTC, Legitgoons approved these changes

2024-10-08 15:24 UTC, Legitgoons commented on .github/workflows/install-and-test.yml
> +          run_install: false
`pnpm` 설치와 `node_modules`설치를 명시적으로 분리하고 싶으셨던거군요? 이해했습니다!

2024-10-08 15:24 UTC, Legitgoons commented on .github/workflows/install-and-test.yml
> +        run: pnpm lint
`혹시 모를 실수`를 잡아내기 위해 CI단계에서도 lint를 실행하겠다는 뜻이군요. workflow의 실행 시간에 많은 영향을 미치지 않는다면, 저도 동의합니다!

2024-10-09 00:24 UTC, suhwan2004 commented
고생하셨습니다! 위에서 질문을 잘 해주셔서 따로 특이사항 없어 approve 해두었습니다!

2024-10-09 00:25 UTC, suhwan2004 approved these changes

2024-10-09 00:30 UTC, merged