🎨 공용 컴포넌트 추가 (드롭다운, 헤더, 페이지 컨테이너)
CollaBu/pennyway-client-webview-next pull request #9
Opened 2024-10-20 16:05 UTC by suhwan2004

## CheckList

- [ V] `gap`을 이용하여 자식 요소간의 간격을 제어하였나요? (iOS 14 미지원으로 gap -> space between 적용)

## 작업 이유
- 공통 컴포넌트(드롭다운, 헤더, 페이지 컨테이너 추가)
- 프로젝트 내 svgr 적용
<br/>

## 작업 사항

### 1️⃣  드롭다운 컴포넌트 추가

Dropdown 컴포넌트의 경우, Shared에 추가하였으며 Dropdonw을 열 버튼과 클릭 시 누르면 나오는 메뉴의 위치(top, right로 자체조정되는...)의 경우 prop으로 받아서 처리하는 것으로 구현해두었습니다.

왠만하면, left, right, middle 다음과 같이 position이라는 const를 만들어서 처리하려 했는데 피그마 확인 시에 right의 끝으로 트리거 버튼이 보이는 케이스가 있으나 이게 진짜 끝에 일자로 붙지 않아서 이건 자체적으로 prop으로 넘겨줘야 되겠구나 생각했던 것 같습니다

<img width="223" alt="image" src="https://github.com/user-attachments/assets/a5cb218a-3ce0-41ff-8610-8f71dd6b4f80">

### 2️⃣  헤더 컴포넌트 구현

Header 컴포넌트의 경우 PageContainer에서밖에 사용되지 않는 컴포넌트이나 일단 분리의 목적으로 Shared에 추가해두었습니다.  이건 PageContainer에 넣을지에 대한 여러분의 의견이 궁금합니다.

페이지 컨테이너의 부속 느낌이다 보니, stories 파일은 따로 만들지 않았습니다.

### 3️⃣ 페이지 컴포넌트 구현

PageContainer의 경우, Header 컴포넌트를 참조하고 있는데 shared에 넣을 시에 동일 계층의 컴포넌트 참조가 되어 widget에 넣어두었습니다.

기본적으로 fixed를 걸고, 헤더의 height 만큼 (현재는, 저희 프로젝트내 헤더는 44px 사용되는 중) margin top을 컨테이너 내 컨텐츠영역을 감싸는 div에 주었습니다. 

래핑하는 컴포넌트이다 보니, stories 파일은 따로 만들지 않았으나, page.tsx에 실적용 시켜두었습니다 ( 헤더 컴포넌트도 여기서 확인 가능합니다!)

### 4️⃣ 프로젝트 내 SVGR 적용

처음에는 디스코드로 svg sprite를 도입하는 방향으로 얘기를 나누었었는데요.  svg sprite를 위한 provider를 만들어서 실제 적용하였을 때 document.body에 react의 포탈로 

```
export default function GlobalSVGProvider() {
  return createPortal(spliteSvgCode, document.body);
}
```

이렇게 spliteSvgCode라는 svg아이콘 덩어리 태그를 넣어주는 로직이 있는데 이부분에서 document의 경우 ssr내 존재하지 않기에, mounted되어 돔이 생성된 후에 이 작업을 해야 해결이 가능했습니다.

아래 참조 url 내 방식처럼 useEffect를 사용하여 이 부분은 해결하였으나, 실제 렌더링 시에 useEffect에서 moutned된 것이 체킹되기 전인 1~2초동안 아이콘이 화면에 안보이는 이슈가 있었습니다.

그래서, 결국은 svg sprite를 포기하고, svgr 세팅을 진행했고 연계로 다음과 같은 작업도 추가로 진행했습니다.
 - turbopack을 쓰는 next.js에 맞춰 추가 세팅 (next.config.mjs 에서 확인 가능합니다.)
 - storybook에서 svgr 적용 안되는 이슈 수정 (storybook 폴더의 main.ts에서 확인 가능합니다)

참고한 주소입니다.
svg sprite 구성
https://velog.io/@adultlee/Svg-sprite-%EA%B8%B0%EB%B2%95%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%82%B4%EA%B0%80-%EC%89%AC%EC%9A%B4-Icon-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EA%B0%9C%EB%B0%9C

svg sprite ssr 내 문제 해결 방법
https://coggiee.medium.com/svg-sprite-icon-%EC%82%AC%EC%9A%A9%EC%8B%9C-%EB%B0%9C%EC%83%9D%ED%95%9C-hydration-error-%EC%B2%98%EB%A6%AC-99f082f08331
<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분

- [ ] 공용 컴포넌트의 재사용성과 확장성이 충분한가요?
- [ ] 공용 컴포넌트의 props 구조가 효율적인가요?
- [ ] 공용 컴포넌트의 폴더 위치가 합당한가요?
  <br/>

## 발견한 이슈

2024-10-21 12:25 UTC, BangDori requested changes
- FSD Architecture에서는 다른 레이어에서 모듈을 불러올 때 [Public API](https://feature-sliced.design/docs/reference/public-api)를 통해 모듈을 불러오도록 규칙을 지켜주셔야 합니다.
- 공용 컴포넌트의 폴더 위치와 근거가 합당했다고 생각합니다.
- 우선 현재는 PR에 대해서는 svgr 방식으로 병합하되 회의를 통해서 svg sprite와 같은 기법의 도입에 대해 고민할 필요가 있다고 생각합니다! (svg-sprite의 장점이 너무나도 크기에...)

2024-10-21 12:25 UTC, BangDori commented on next.config.mjs
> +        },
P4: 현재 해당 라인은 Turbopack을 사용할 때 적용되는 규칙으로 보여지는데 현재 package.json에서는 개발 서버 스크립트에 Turbopack 활성화 플래그가 추가되어 있지 않은 것 같아요!

2024-10-21 12:25 UTC, BangDori commented on src/shared/ui/header/ui/Header.tsx
> +  left?: JSX.Element;
P4: 피그마를 확인했을 때 헤더의 left는 항상 존재하는 것으로 보이는데 left에 대한 타입을 optional로 지정하신 이유가 있으신가요?

2024-10-21 12:25 UTC, BangDori commented on src/widgets/pageContainer/ui/PageContainer.tsx
> +import type { IHeader } from '@/shared/ui/header/ui/Header';
P2: FSD Architecture에서는 다른 레이어에서 모듈을 불러올 때 [Public API](https://feature-sliced.design/docs/reference/public-api)를 통해 모듈을 불러오도록 규칙을 지켜야 합니다!

2024-10-21 12:25 UTC, BangDori commented on src/shared/ui/dropdown/ui/Dropdown.stories.tsx
> +import type { IOption } from '@/shared/ui/dropdown/ui/Dropdown';
P3: 슬라이스 내부에서는 다른 모듈을 가져올 때 절대 경로를 사용할 필요가 없지 않을까요?

2024-10-21 12:25 UTC, BangDori commented on src/shared/ui/dropdown/ui/Dropdown.tsx
> +  );
P4: PR에서 업로드해주신 이미지를 확인해보면, DropDown 컴포넌트에서 선택된 상태가 아니라 Hover된 상태로 보여지는데 현재 선택된 메뉴를 상태로 관리할 필요가 없지 않을까요?

2024-10-21 12:25 UTC, BangDori commented on src/shared/ui/dropdown/ui/Dropdown.tsx
> +  selectOption: (index: number) => void;
P5: selectOption props가 어떤 동작을 하는지 잘 이해가 되지 않는데, 혹시 설명을 부탁드려도 될까요?

2024-10-21 12:25 UTC, BangDori commented on src/widgets/pageContainer/ui/PageContainer.tsx
> +}: PropsWithChildren<IPageContainer>) {
P5: 저는 ModalWrapper 컴포넌트를 구현할 때 PropsWithChildren 타입을 상속받도록 했었는데 제네릭을 이용하는 방식이 더 간결하고 가독성도 좋은 거 같네요!! 👍 저도 이렇게 수정해야 겠어요!

2024-10-21 12:59 UTC, suhwan2004 commented on src/shared/ui/dropdown/ui/Dropdown.stories.tsx
> +import type { IOption } from '@/shared/ui/dropdown/ui/Dropdown';
말씀주신 게 맞는 것 같습니다. 습관적으로 절대경로를 쓴 것 같아요! 빠른 수정해두겠습니다!

2024-10-21 12:59 UTC, suhwan2004 commented on src/shared/ui/header/ui/Header.tsx
> +  left?: JSX.Element;
음 헤더 컴포넌트를 만들 때, 추후에 left가 존재하지 않는 헤더 케이스가 존재할 수 있을까?라는 의문을 가지고 left를 옵셔널로 처리해둔 것 같아요! 이런 경우에는 병준님의 경우 어떻게 처리하시는지 궁금합니다

2024-10-21 12:59 UTC, suhwan2004 commented on src/widgets/pageContainer/ui/PageContainer.tsx
> +import type { IHeader } from '@/shared/ui/header/ui/Header';
앗 감사합니다! 바로 수정해둘게요

2024-10-21 12:59 UTC, suhwan2004 commented on src/shared/ui/dropdown/ui/Dropdown.tsx
> +  );
아! 제가 피그마 확인을 제대로 못한 것 같습니다. 아래 피그마로 다시 확인해보니 웹뷰에서 active 되었을 때의 색깔이군요... 빠른 수정 해둘께요!

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/1444a473-09a6-4f40-987c-c892e52de969">

2024-10-21 12:59 UTC, suhwan2004 commented on src/shared/ui/dropdown/ui/Dropdown.tsx
> +  selectOption: (index: number) => void;
부모 컴포넌트에서 다음과 같이 선택된 옵션을 확인하기 위한 optionIdx와 같은 예시의 상태가 있고

부모에서 Dropdown을 쓸 때, selectOption에 prop으로 받은 index를 부모의 optionIdx를 갱신해주는 로직의 함수를 넣어주고

```
const [optionIdx, setOptionIdx] = useState(0)
...


const clickOption = (index : number) =>  setOptionIdx (index)



return(
   ...
   <Dropdown
     ...
     selectOption={clickOption}
     />
    ...
)
```



자식 컴포넌트에서 특정 드롭다운 내 옵션 클릭시 다음과 같이 동작되는 것을 염두하여 코드를 짰던 것 같습니다!

```
const clickOption = (index: number) => {
    setSelectedIndex(index); // => 자식 내 저장하는 인덱스 값 변경 (수정 후 사라질 예정)
    setIsOpen(false);  // => 특정 옵션을 선택했기 때문에 드롭다운  닫힘
    selectOption(index);  // => 방금 선택한 인덱스를 이용해 부모에 있는 optionIdx를 갱신하기
  };

```

2024-10-21 12:59 UTC, suhwan2004 commented on next.config.mjs
> +        },
아... 이걸 확인 안하고 그냥 넣어버렸군요... 10줄의 experimental 없이 작동되는지 확인 후 큰 문제 없다면 수정해두겠습니다!

2024-10-21 14:57 UTC, BangDori reviewed
이전 리뷰에서 놓친 내용이 있어서 아래 리뷰들도 같이 확인 부탁드릴게요!!!

2024-10-21 14:57 UTC, BangDori commented on src/shared/ui/header/ui/Header.tsx
> +  left?: JSX.Element;
미래에 일어날 혹은 미래를 대비한 확장성있는 코드는 중요하지만 저는 미래를 완전히 대비할 수 있는 코드는 없다고 생각해요. 그래서 우선 현재에 집중하되 추후 변경에 유연하도록 코드를 작성하는 게 가장 좋은 것 같아요.

그래서 저라면 현 상황에서는 left를 required로 지정하고 만약 left가 없는 경우가 발생하게 된다면 그 시점에서 optional로 설정할 지를 팀원들과 의논해볼 거 같아요! left만 없는게 아니라 다른 추가적인 요소가 생길수도 있으니!

2024-10-21 14:57 UTC, BangDori commented on src/shared/ui/header/ui/Header.tsx
> +    <header className="fixed top-0 left-0 z-50 flex items-center justify-between h-[44px] w-full bg-white">
P3: 아 그리고 리뷰하면서 놓쳤었는데 요기서 left와 center 주어지는 경우에는 left와 center가 각자의 포지션에 맞게 위치하는 게 아니라 justify-between으로 인해서 끝으로 배치되는 것 같아요!

2024-10-21 14:57 UTC, BangDori commented on src/shared/ui/dropdown/ui/Dropdown.stories.tsx
> +    const [selectedOptionIndex, setSelectedOptionIndex] = useState<number>(0);
P4: `selectedOptionIndex`의 값을 0으로 할당함으로써 타입스크립트의 타입 시스템은 `selectedOptionIndex`는 숫자라는 것을 유추할 수 있기 때문에 굳이 타입 지정을 해주지 않아도 될 것 같아요!

2024-10-21 14:57 UTC, BangDori commented on src/shared/ui/dropdown/ui/Dropdown.stories.tsx
> +        }}
P5: 사실 별로 중요한 부분은 아니지만, selectOption props에 함수를 전달할 때 익명 함수를 생성하여 전달하는 방식말고 함수의 참조를 전달하는 방식은 어떻게 생각하세요?

2024-10-21 14:57 UTC, BangDori commented on src/shared/ui/dropdown/ui/Dropdown.tsx
> +  selectOption: (index: number) => void;
<div align="center">
<img src="https://github.com/user-attachments/assets/d895969b-0bba-4d68-bf27-46665f3e2d91" />
</div>

엇 질문이 있는데 혹시 해당 Dropdown 컴포넌트는 PR에 올려주신 이미지와 공개 범위를 선택하는 위 이미지를 모두 커버하기 위한 컴포넌트일까요?

2024-10-22 13:17 UTC, suhwan2004 commented on src/shared/ui/dropdown/ui/Dropdown.tsx
> +  selectOption: (index: number) => void;
넵넵! 버튼의 경우 children으로 커스텀에 하단 드롭다운 포함한 컴포넌트입니다

2024-10-22 13:18 UTC, suhwan2004 commented on src/shared/ui/dropdown/ui/Dropdown.stories.tsx
> +        }}
stories라서 큰 생각없이 작성했던 것 같네요... 좋아요! 빠른 수정해둘께요

2024-10-22 13:19 UTC, suhwan2004 commented on src/shared/ui/dropdown/ui/Dropdown.stories.tsx
> +    const [selectedOptionIndex, setSelectedOptionIndex] = useState<number>(0);
말씀대로 굳이 명시적으로 타입 지정을 할 필요가 없을 것 같네요... 수정해두겠습니다!

2024-10-22 13:23 UTC, suhwan2004 commented on src/shared/ui/header/ui/Header.tsx
> +  left?: JSX.Element;
사실상, 디자인을 갈아엎지 않는 한 optional이 필요없기도 하고, 말씀주신 의견에서 추가적인 요소가 발생할 수 있다는 것 까지 생각하면 병준님 의견에 감화되는 것 같습니다! 수정해둘께요

2024-10-22 13:47 UTC, suhwan2004 commented on src/shared/ui/header/ui/Header.tsx
> +    <header className="fixed top-0 left-0 z-50 flex items-center justify-between h-[44px] w-full bg-white">
<img width="386" alt="image" src="https://github.com/user-attachments/assets/a09c7a8e-1ded-4a67-a7f5-48e106d0e9c4">

약간, 의도적인 느낌이긴 한데 검색 페이지의 헤더를 고려했던 것 같습니다. 그 이외에, 3개가 다 안 들어올 시에 3분할이 안되는 스타일의 경우, 빈 것은 빈 div 태그를 넘겨줘서 해결할까?라는 고민을 하며 짰던 것 같아요

2024-10-22 16:44 UTC, BangDori commented on src/shared/ui/header/ui/Header.tsx
> +  left?: JSX.Element;
넵! 확인 완료했습니다 좋은 고민거리를 던져주셔서 감사합니다!!

2024-10-22 16:49 UTC, BangDori commented on src/shared/ui/header/ui/Header.tsx
> +    <header className="fixed top-0 left-0 z-50 flex items-center justify-between h-[44px] w-full bg-white">
아하 그런 의도가 있었군요, 수환님 말씀대로 빈 부분에 대해서는 div 태그를 넘겨주는 방식을 활용하면 3개의 props를 모두 가지면서 필요한 부분만 원하는대로 사용할 수 있겠네요.

빈 태그를 넘겨줌으로써 모든 헤더를 커버하는 건 생각지도 못한 방식이였는데 정말 좋은 방법이네요.. 👍

2024-10-22 17:02 UTC, BangDori approved these changes
수환님 코드를 리뷰하면서 이해하려고 많은 고민을 했는데, 고민한 시간이 전혀 아깝지 않았던 시간이였네요. 수환님이 얼마나 범용성과 확장성을 고려하시면서 코드를 작성하시는지에 대해 배울 수 있었습니다..!

이번 PR에서 많은 배움을 주셔서 감사합니다. 현재 Resolve되지 않은 코멘트들은 수환님이 확인하시고 Resolve 처리 하시면 될 거 같습니다!! 고생하셨습니다

2024-10-22 17:02 UTC, BangDori commented on src/shared/ui/dropdown/ui/Dropdown.tsx
> +  selectOption: (index: number) => void;
![image](https://github.com/user-attachments/assets/fba87c87-ce24-4315-9ebe-403240e0f7ca)

아 제가 계속해서 질문을 드린 이유는 `selectOption` props가 위 이미지와 같이 각각의 option에 다른 이벤트가 다뤄지는 경우에도 적합한 props일까?를 생각하다보니 계속해서 질문을 드리게 된 것 같아요.

생각해보니 수찬님이 말씀해주신 대로 상위 컴포넌트에서 index를 매개변수로 받아 매개변수를 이용해 해당 option에 대한 이벤트를 처리를 한다면 무리없이 DropDown을 사용할 수 있을 것 같네요!

2024-10-22 17:02 UTC, BangDori commented on src/shared/ui/header/ui/Header.tsx
> +    <header className="fixed top-0 left-0 z-50 flex items-center justify-between h-[44px] w-full bg-white">
아하 그런 의도가 있었군요, 수환님 말씀대로 빈 부분에 대해서는 div 태그를 넘겨주는 방식을 활용하면 3개의 props를 모두 가지면서 필요한 부분만 원하는대로 사용할 수 있겠네요.

빈 태그를 넘겨줌으로써 모든 헤더를 커버하는 건 생각지도 못한 방식이였는데 정말 좋은 방법이네요.. 👍

2024-10-23 13:13 UTC, merged